from sqlalchemy import Column, Integer, Date, ForeignKey, String, DECIMAL
from sqlalchemy.dialects.postgresql import MONEY
from sqlalchemy.orm import relationship, Session

from serenity.equity.sharadar_api import Base


class Fundamentals(Base):
    __tablename__ = 'fundamentals'

    fundamentals_id = Column(Integer, primary_key=True)
    ticker_id = Column(Integer, ForeignKey('ticker.ticker_id'))
    ticker = relationship('Ticker')
    dimension_type_id = Column(Integer, ForeignKey('dimension_type.dimension_type_id'))
    dimension_type = relationship('DimensionType')
    calendar_date = Column(Date)
    date_key = Column(Date)
    report_period = Column(Date)
    last_updated = Column(Date)
    accoci = Column(MONEY)
    assets = Column(MONEY)
    assets_avg = Column(MONEY)
    assets_c = Column(MONEY)
    assets_nc = Column(MONEY)
    asset_turnover = Column(DECIMAL)
    bvps = Column(DECIMAL)
    capex = Column(MONEY)
    cash_neq = Column(MONEY)
    cash_neq_usd = Column(MONEY)
    cor = Column(MONEY)
    consol_inc = Column(MONEY)
    current_ratio = Column(MONEY)
    de = Column(MONEY)
    debt = Column(MONEY)
    debt_c = Column(MONEY)
    debt_nc = Column(MONEY)
    debt_usd = Column(MONEY)
    deferred_rev = Column(MONEY)
    dep_amor = Column(MONEY)
    deposits = Column(MONEY)
    div_yield = Column(DECIMAL)
    dps = Column(MONEY)
    ebit = Column(MONEY)
    ebitda = Column(MONEY)
    ebitda_margin = Column(DECIMAL)
    ebitda_usd = Column(MONEY)
    ebit_usd = Column(MONEY)
    ebt = Column(MONEY)
    eps = Column(MONEY)
    eps_dil = Column(MONEY)
    eps_usd = Column(MONEY)
    equity = Column(MONEY)
    equity_avg = Column(MONEY)
    equity_usd = Column(MONEY)
    ev = Column(DECIMAL)
    ev_ebit = Column(DECIMAL)
    ev_ebitda = Column(DECIMAL)
    fcf = Column(MONEY)
    fcf_ps = Column(MONEY)
    fx_usd = Column(MONEY)
    gp = Column(MONEY)
    gross_margin = Column(DECIMAL)
    int_exp = Column(MONEY)
    inv_cap = Column(MONEY)
    inv_cap_avg = Column(MONEY)
    inventory = Column(MONEY)
    investments = Column(MONEY)
    investments_c = Column(MONEY)
    investments_nc = Column(MONEY)
    liabilities = Column(MONEY)
    liabilities_c = Column(MONEY)
    liabilities_nc = Column(MONEY)
    market_cap = Column(MONEY)
    ncf = Column(MONEY)
    ncf_bus = Column(MONEY)
    ncf_common = Column(MONEY)
    ncf_debt = Column(MONEY)
    ncf_div = Column(MONEY)
    ncf_f = Column(MONEY)
    ncf_i = Column(MONEY)
    ncf_inv = Column(MONEY)
    ncf_o = Column(MONEY)
    ncf_x = Column(MONEY)
    net_inc = Column(MONEY)
    net_inc_cmn = Column(MONEY)
    net_inc_cmn_usd = Column(MONEY)
    net_inc_dis = Column(MONEY)
    net_inc_nci = Column(MONEY)
    net_margin = Column(DECIMAL)
    op_ex = Column(MONEY)
    op_inc = Column(MONEY)
    payables = Column(MONEY)
    payout_ratio = Column(DECIMAL)
    pb = Column(DECIMAL)
    pe = Column(DECIMAL)
    pe1 = Column(DECIMAL)
    ppne_net = Column(MONEY)
    pref_div_is = Column(MONEY)
    price = Column(MONEY)
    ps = Column(MONEY)
    ps1 = Column(MONEY)
    receivables = Column(MONEY)
    ret_earn = Column(MONEY)
    revenue = Column(MONEY)
    revenue_usd = Column(MONEY)
    rnd = Column(MONEY)
    roa = Column(DECIMAL)
    roe = Column(DECIMAL)
    roic = Column(DECIMAL)
    ros = Column(DECIMAL)
    sb_comp = Column(MONEY)
    sgna = Column(MONEY)
    share_factor = Column(DECIMAL)
    shares_bas = Column(Integer)
    shares_wa = Column(Integer)
    shares_wa_dil = Column(Integer)
    sps = Column(DECIMAL)
    tangibles = Column(MONEY)
    tax_assets = Column(MONEY)
    tax_exp = Column(MONEY)
    tax_liabilities = Column(MONEY)
    tbvps = Column(DECIMAL)
    working_capital = Column(MONEY)


class DimensionType(Base):
    __tablename__ = 'dimension_type'

    dimension_type_id = Column(Integer, primary_key=True)
    dimension_type_code = Column(String(16))

    @classmethod
    def find_by_code(cls, session: Session, dimension_type_code: str):
        return session.query(DimensionType).filter(DimensionType.dimension_type_code ==
                                                   dimension_type_code).one_or_none()

    @classmethod
    def get_or_create(cls, session: Session, dimension_type_code: str):
        dimension_type = DimensionType.find_by_code(session, dimension_type_code)
        if dimension_type is None:
            dimension_type = DimensionType(dimension_type_code=dimension_type_code)
            session.add(dimension_type)
        return dimension_type
