{
 "title": "Marketdata",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Distributor - Republishes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(trade_republish_counter_total[1m]))"
    }
   ]
  },
  {
   "title": "Feedhandler - Trade Prints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(trade_counter_total[1m]))"
    },
    {}
   ]
  },
  {
   "title": "Order Book Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(book_update_counter_total[1m]))\n"
    },
    {}
   ]
  }
 ]
}