{
 "title": "Marketdata",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Distributor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distributor - Trade Republishes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(trade_republish_counter_total[1m]))"
    }
   ]
  },
  {
   "title": "Distributor - Book Delta Republishes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(book_delta_republish_counter_total[1m]))"
    }
   ]
  },
  { "title": "Feedhandler Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Feedhandler - Trade Prints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(trade_counter_total[1m]))"
    },
    {}
   ]
  },
  {
   "title": "Feedhandler - Order Book Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(book_update_counter_total[1m]))\n"
    },
    {}
   ]
  }
 ]
}