GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA serenity TO serenitydb;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA serenity TO serenitydb;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA serenity TO serenitydb;