GRANT USAGE ON SCHEMA serenity TO serenity;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA serenity TO serenity;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA serenity TO serenity;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA serenity TO serenity;