GRANT USAGE ON SCHEMA sharadar TO sharadar;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sharadar TO sharadar;
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA sharadar TO sharadar;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA sharadar TO sharadar;